server:
  port: 0

spring:
  application:
    name: blur-match
  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
  h2:
    console:
      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      settings:
        web-allow-others: true
      path: /h2-console  # H2 Console? Path
  # Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver  # Database? H2? ?????.
    url: jdbc:h2:mem:test  # H2 ?? ??
    username: sa  # H2 ?? ? ??? username ?? (??? ??? ??)
    password:  # H2 ?? ? ??? password ?? (??? ??? ??)

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true





