server:
  port: 8000

spring:
  application:
    name: blur-gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: blur-auth
          uri: lb://BLUR-AUTH
          predicates:
            - Path=/blur-auth/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/blur-auth/(?<segment>.*), /$\{segment}
        - id: blur-auth
          uri: lb://BLUR-AUTH
          predicates:
            - Path=/blur-auth/user/register
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/blur-auth/(?<segment>.*), /$\{segment}
        - id: blur-auth
          uri: lb://BLUR-AUTH
          predicates:
            - Path=/blur-auth/**
            - Method=GET            
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/blur-auth/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter

        - id: blur-profile
          uri: lb://BLUR-PROFILE
          predicates:
            - Path=/blur-profile/**
            - Method= GET, POST, PUT
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/blur-profile/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter
        - id: blur-match
          uri: lb://BLUR-MATCH
          predicates:
            - Path=/blur-match/**
            - Method= GET, POST, PUT
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/blur-match/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter
        - id: blur-chat
          uri: lb://BLUR-CHAT
          predicates:
            - Path=/blur-chat/**
            - Method= GET, POST, PUT
          filters:
            - RewritePath=/blur-chat/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Cookie

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

token:
  secret: blurUserTokenblurUserTokenblurUserTokenblurUserTokenblurUserTokenblurUserTokenblurUserTokenblurUserToken